
# Top level defaults
title: Esaan Tumbar
description: Esaan Tumbar is a gourmet, Northeast-Thailand style restaurant in Mclean, Virginia.
permalink: /:categories/:title
baseurl: /esaan

sass:
  style: compressed # possible values: nested, expanded, compact, and compressed

# Plugins
plugins:
  - jekyll-sitemap

# Defaults for different page types
defaults:
  -
    scope:
      path: "assets/**/*.pdf"
    values:
      sitemap: false
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default