
# Top level defaults
title: Esaan Tumbar
description: Esaan Tumbar is a gourmet, Northeast-Thailand style restaurant in Mclean, Virginia.
permalink: /:categories/:title
baseurl: /esaan

sass:
  style: compressed # possible values: nested, expanded, compact, and compressed

# Plugins
plugins:
  - jekyll-sitemap

# Collections
collections:
  apps:
    permalink: /:collection/:name
    output: true
  beef:
    permalink: /:collection/:name
    output: true
  chicken:
    permalink: /:collection/:name
    output: true
  fish:
    permalink: /:collection/:name
    output: true
  pork:
    permalink: /:collection/:name
    output: true
  seafood:
    permalink: /:collection/:name
    output: true
  somtum:
    permalink: /:collection/:name
    output: true
  veggie:
    permalink: /:collection/:name
    output: true
collections_dir: _food

# Defaults for different page types
defaults:
  -
    scope:
      path: "assets/**/*.pdf"
    values:
      sitemap: false
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default